### PR TITLE
Hotfix/slice out of range

### PR DESCRIPTION
**Pull request by DarianShawn**
# Description

The evm crash due to out of range copy in `evm.opReturnDataCopy`. The crash log is blow.

This PR fixes it.

```
Oct  2 15:07:33 dogechain-validator dogechain[312072]: panic: runtime error: slice bounds out of range [128:128+96]
Oct  2 15:07:33 dogechain-validator dogechain[312072]: goroutine 33 [running]:
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.opReturnDataCopy(0xc047dc8480)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/instructions.go:841 +0x3b0
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.(*state).Run(0xc047dc8480)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/state.go:245 +0x110
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.(*EVM).Run(0x2cf8650, 0xc04b9c7340, {0x1e073e0, 0xc03c77ba00}, 0xc03c77ba30)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/evm.go:45 +0x15f
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).run(0xc03c77ba00, 0x33abfdbd9f0c5423, {0x1e073e0, 0xc03c77ba00})
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:632 +0x16f
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).applyCall(0xc03c77ba00, 0xc04b9c7340, 0x0, {0x1e073e0, 0xc03c77ba00})
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:685 +0x2b3
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).Callx(0xc043c4efc0, 0xf1, {0x1e073e0, 0xc03c77ba00})
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:855 +0x45
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.opCall.func1(0xc043c4efc0)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/instructions.go:1162 +0x2a4
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.(*state).Run(0xc043c4efc0)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/state.go:245 +0x110
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state/runtime/evm.(*EVM).Run(0x2cf8650, 0xc04b9c6bb0, {0x1e073e0, 0xc03c77ba00}, 0xc03c77ba30)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/runtime/evm/evm.go:45 +0x15f
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).run(0xc03c77ba00, 0x3b6cc2a6dcceefff, {0x1e073e0, 0xc03c77ba00})
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:632 +0x16f
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).applyCall(0xc03c77ba00, 0xc04b9c6bb0, 0x0, {0x1e073e0, 0xc03c77ba00})
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:685 +0x2b3
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).Call2(0xc03c77ba00, {0x3c, 0xd6, 0x51, 0x4c, 0x97, 0xda, 0xf9, 0xa, 0xff, ...}, ...)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:626 +0x265
Oct  2 15:07:33 dogechain-validator dogechain[312072]: github.com/dogechain-lab/dogechain/state.(*Transition).apply(0xc03c77ba00, 0xc042fc35e0)
Oct  2 15:07:33 dogechain-validator dogechain[312072]: #011/go/src/state/executor.go:585 +0xd0c
```

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [x] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

**Comment by DarianShawn** [comment]
@zivkovicmilos Hi, zivkov. Bad news right now.
Do Polygon Edge team has any idea about this? Same `evm` codes in the upstream repo.

Would be very helpful if your guys could do us a favor to go through this PR.

**Comment by Kourin1996** [comment]
@DarianShawn Hello, can I ask a question? What was the direct reason to cause this issue? Negative check of dataOffset seems to be only a change.

**Comment by DarianShawn** [comment]
I'm afraid we don't get more information, the logs have been rotated after restarting. System messages just print out the crash stack, not any contract details.

I've tried using `cap()` in `checkMemory()`, but it panic in the `ethereum` evm tests.

**Comment by Kourin1996** [comment]
@DarianShawn Thank you for quick reply. Just confirm. Have you seen the same crash after you fixed and restarted it? or you do no longer see this?

**Comment by DarianShawn** [comment]
The hot fix is not deployed yet, and yes, another crash appeared one hour later.
I guess some one gave another shot, but found it failed and quit.

What if we use `recover()` in `state.Run()`? Anyway, `evm` should not crash, but provide more logs.

**Comment by Kourin1996** [comment]
@DarianShawn I guess it can be caused with the bytecode which are not generated by any compiler. I mean negative value can be stacked before calling. `recover()` is a safe-guard for it and you can show several info and state like memory, stack, code, and etc.

**Comment by DarianShawn** [comment]
Alright, my guess is the same.

Such a transaction should be considered a failure to execute, `recover()` would be more elegant way to do so.
Check with this demo: https://go.dev/play/p/rejPoGEQTGL

**Comment by Kourin1996** [comment]
@DarianShawn 
I found the another issue related to this. Panic happens if the size is zero but memOffset is negative because checkMemory passes. I think checkMemory should check negativity of size and length first. How do you think?

You might want to change the order of checks in `memoryCheck`

**Comment by DarianShawn** [comment]
@Kourin1996 You're right. Updated in 7aa3a8ab.

**Comment by zivkovicmilos** [comment]
Hey @DarianShawn,

You can check out the parallel fix PR we have going on for the Edge repo:
https://github.com/0xPolygon/polygon-edge/pull/778

**Comment by DarianShawn** [comment]
Thanks, @zivkovicmilos 
I'll keep an eye on it.

**Review by abrahamcruise321 — APPROVED** [review]
good job! LGTM.

**Pull request merged**
