### PR TITLE
replace sync.Map

### PR DESCRIPTION
**Pull request by 0xcb9ff9**
# Description

replace sync.Map 

Why is this needed:
https://github.com/golang/go/issues/40999

there are 2 issues:

1. go 15.1 introduced a regression, that keys in sync.Map.dirty are not deleted
2. even in go 1.14, keys in sync.Map.read are not purged immediately, see comments at the end

# Changes include

- [x] Bugfix (non-breaking change that solves an issue)
- [ ] Hotfix (change that solves an urgent issue, and requires immediate attention)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the relevant labels
- [ ] I have updated the official documentation
- [ ] I have added sufficient documentation in code

## Testing

- [x] I have tested this code with the official test suite
- [ ] I have tested this code manually

### CODE REVIEW

**Review by DarianShawn — CHANGES_REQUESTED** [review]
@0xcb9ff9 A nice shot.

Still get some questions here:
* How is the performance when using `common.ConcurrentMap` instead of `sync.Map`?
  * We need some benchmark comparison between those two solutions.
* If you want to provide a drop-down replacement of `sync.Map`, I would suggest not expose more APIs then it.
* What if providing more specific type map in each business logic, instead of using runtime assertion one?
* Never use `common`, `utils`, `functions` etc package name, they're ambiguous. Try `concurrentmap` or `syncmap` instead.

**Comment by 0xcb9ff9** [comment]
@DarianShawn It's been tested by someone, it's an old question, The current `sync.Map` implementation is not good, it is worse than the simplified `map + sync.RWMutex`, It can be modified to sharding locks in the future (like [concurrent-map](https://github.com/orcaman/concurrent-map))

[golang/go#28938](https://github.com/golang/go/issues/28938)
[golang/go#21035](https://github.com/golang/go/issues/21035)
[golang/go#47643](https://github.com/golang/go/issues/47643)

**Comment by 0xcb9ff9** [comment]
@DarianShawn benchmark results

use `sync.Map`
dev branch (5f4f1a38)

```
root@9f69ebf63463:/work# go test -benchmem -count=3 -run=^$ -bench ^BenchmarkPruneStaleAccounts100KAccounts$ github.com/dogechain-lab/dogechain/txpool
goos: linux
goarch: amd64
pkg: github.com/dogechain-lab/dogechain/txpool
cpu: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
BenchmarkPruneStaleAccounts100KAccounts-16    	      82	  13443283 ns/op	  269576 B/op	    1220 allocs/op
BenchmarkPruneStaleAccounts100KAccounts-16    	      86	  13168944 ns/op	  277700 B/op	    1164 allocs/op
BenchmarkPruneStaleAccounts100KAccounts-16    	      86	  13126742 ns/op	  257031 B/op	    1163 allocs/op
PASS
ok  	github.com/dogechain-lab/dogechain/txpool	16.029s
```
use `ConcurrentMap`
commit (acd3b938)

```
root@9f69ebf63463:/work# go test -benchmem -count=3 -run=^$ -bench ^BenchmarkPruneStaleAccounts100KAccounts$ github.com/dogechain-lab/dogechain/txpool
goos: linux
goarch: amd64
pkg: github.com/dogechain-lab/dogechain/txpool
cpu: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
BenchmarkPruneStaleAccounts100KAccounts-16    	     127	   8534692 ns/op	  218225 B/op	    1577 allocs/op
BenchmarkPruneStaleAccounts100KAccounts-16    	     134	   8750662 ns/op	  206825 B/op	    1495 allocs/op
BenchmarkPruneStaleAccounts100KAccounts-16    	     136	   9093683 ns/op	  203788 B/op	    1473 allocs/op
PASS
ok  	github.com/dogechain-lab/dogechain/txpool	15.688s
```

**Review by DarianShawn — APPROVED** [review]
LGTM

**Pull request merged**
